### PR TITLE
Updates to documentation adding a license, and preparing for 1.0.0

### PR DESCRIPTION
**Pull request by mdobson**
- Fleshed out a README with examples, descriptions of methods, and license
- Added a LICENSE file

### CODE REVIEW

**Comment by kevinswiber** [comment]
Should we explain argo-resource a little?  I use that pretty frequently with Titan.  Also, there's this whole automatic resource loader thing I created.  I use it from time to time.

**Comment by mdobson** [comment]
Automatic resource loader?

**Comment by kevinswiber** [comment]
Resource factories.  See the directory resource factory thing in action here:  https://github.com/argo/titan/blob/master/example/advanced/server.js#L10

**Comment by mdobson** [comment]
I'm not super familiar with the feature. Would you be able to add a doc for
it in the README?

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!
[image: http://iloveapis.com/]

**Comment by mdobson** [comment]
- Created a PR for an argo-resource README. We link to it in this README. 
- Also added docs for the load function.

**Comment by kevinswiber** [comment]
I think what you have is good enough for now.  Not sure we need to explain the resource factory concept.

+1, Merge away.

**Pull request merged**
